//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.23 at 04:09:43 PM CET 
//


package it.polito.nffg.neo4j.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.nffg.neo4j.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
	
    private final static QName _Nffg_QNAME = new QName("http://www.example.org/nffg/", "nffg");
    private final static QName _NffgSet_QNAME = new QName("http://www.example.org/nffg/", "nffg-set");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.nffg.neo4j.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FlowrulesType }
     * 
     */
    public FlowrulesType createFlowrulesType() {
        return new FlowrulesType();
    }

    /**
     * Create an instance of {@link FlowrulesType.Flowspace }
     * 
     */
    public FlowrulesType.Flowspace createFlowrulesTypeFlowspace() {
        return new FlowrulesType.Flowspace();
    }

    /**
     * Create an instance of {@link CiType }
     * 
     */
    public CiType createCiType() {
        return new CiType();
    }

    /**
     * Create an instance of {@link CiType.Attributes }
     * 
     */
    public CiType.Attributes createCiTypeAttributes() {
        return new CiType.Attributes();
    }

    /**
     * Create an instance of {@link EpType }
     * 
     */
    public EpType createEpType() {
        return new EpType();
    }

    /**
     * Create an instance of {@link SpecType }
     * 
     */
    public SpecType createSpecType() {
        return new SpecType();
    }

    /**
     * Create an instance of {@link MonParamsType }
     * 
     */
    public MonParamsType createMonParamsType() {
        return new MonParamsType();
    }

    /**
     * Create an instance of {@link NffgSet }
     * 
     */
    public NffgSet createNffgSet() {
        return new NffgSet();
    }

    /**
     * Create an instance of {@link Nffg }
     * 
     */
    public Nffg createNffg() {
        return new Nffg();
    }

    /**
     * Create an instance of {@link EpointsType }
     * 
     */
    public EpointsType createEpointsType() {
        return new EpointsType();
    }

    /**
     * Create an instance of {@link NfunctionsType }
     * 
     */
    public NfunctionsType createNfunctionsType() {
        return new NfunctionsType();
    }

    /**
     * Create an instance of {@link NelementsType }
     * 
     */
    public NelementsType createNelementsType() {
        return new NelementsType();
    }

    /**
     * Create an instance of {@link CpointsType }
     * 
     */
    public CpointsType createCpointsType() {
        return new CpointsType();
    }

    /**
     * Create an instance of {@link NfType }
     * 
     */
    public NfType createNfType() {
        return new NfType();
    }

    /**
     * Create an instance of {@link EpCpType }
     * 
     */
    public EpCpType createEpCpType() {
        return new EpCpType();
    }

    /**
     * Create an instance of {@link EpsCpsType }
     * 
     */
    public EpsCpsType createEpsCpsType() {
        return new EpsCpsType();
    }

    /**
     * Create an instance of {@link ActionsType }
     * 
     */
    public ActionsType createActionsType() {
        return new ActionsType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link PortType }
     * 
     */
    public PortType createPortType() {
        return new PortType();
    }

    /**
     * Create an instance of {@link CpType }
     * 
     */
    public CpType createCpType() {
        return new CpType();
    }

    /**
     * Create an instance of {@link CtrlInterfacesType }
     * 
     */
    public CtrlInterfacesType createCtrlInterfacesType() {
        return new CtrlInterfacesType();
    }

    /**
     * Create an instance of {@link NeType }
     * 
     */
    public NeType createNeType() {
        return new NeType();
    }

    /**
     * Create an instance of {@link Paths }
     * 
     */
    public Paths createPaths() {
        return new Paths();
    }

    /**
     * Create an instance of {@link HttpMessage }
     * 
     */
    public HttpMessage createHttpMessage() {
        return new HttpMessage();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link FlowrulesType.Flowspace.Mac }
     * 
     */
    public FlowrulesType.Flowspace.Mac createFlowrulesTypeFlowspaceMac() {
        return new FlowrulesType.Flowspace.Mac();
    }

    /**
     * Create an instance of {@link FlowrulesType.Flowspace.Ip }
     * 
     */
    public FlowrulesType.Flowspace.Ip createFlowrulesTypeFlowspaceIp() {
        return new FlowrulesType.Flowspace.Ip();
    }

    /**
     * Create an instance of {@link FlowrulesType.Flowspace.Tcp }
     * 
     */
    public FlowrulesType.Flowspace.Tcp createFlowrulesTypeFlowspaceTcp() {
        return new FlowrulesType.Flowspace.Tcp();
    }

    /**
     * Create an instance of {@link FlowrulesType.Flowspace.Udp }
     * 
     */
    public FlowrulesType.Flowspace.Udp createFlowrulesTypeFlowspaceUdp() {
        return new FlowrulesType.Flowspace.Udp();
    }

    /**
     * Create an instance of {@link CiType.Attributes.Attribute }
     * 
     */
    public CiType.Attributes.Attribute createCiTypeAttributesAttribute() {
        return new CiType.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link EpType.Flowspace }
     * 
     */
    public EpType.Flowspace createEpTypeFlowspace() {
        return new EpType.Flowspace();
    }

    /**
     * Create an instance of {@link SpecType.Deployment }
     * 
     */
    public SpecType.Deployment createSpecTypeDeployment() {
        return new SpecType.Deployment();
    }

    /**
     * Create an instance of {@link SpecType.Image }
     * 
     */
    public SpecType.Image createSpecTypeImage() {
        return new SpecType.Image();
    }

    /**
     * Create an instance of {@link SpecType.Cpu }
     * 
     */
    public SpecType.Cpu createSpecTypeCpu() {
        return new SpecType.Cpu();
    }

    /**
     * Create an instance of {@link SpecType.Memory }
     * 
     */
    public SpecType.Memory createSpecTypeMemory() {
        return new SpecType.Memory();
    }

    /**
     * Create an instance of {@link SpecType.Storage }
     * 
     */
    public SpecType.Storage createSpecTypeStorage() {
        return new SpecType.Storage();
    }

    /**
     * Create an instance of {@link MonParamsType.Parameter }
     * 
     */
    public MonParamsType.Parameter createMonParamsTypeParameter() {
        return new MonParamsType.Parameter();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NffgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/nffg/", name = "nffg")
    public JAXBElement<Nffg> createNffg(Nffg value) {
        return new JAXBElement<Nffg>(_Nffg_QNAME, Nffg.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NffgSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/nffg/", name = "nffg-set")
    public JAXBElement<NffgSet> createNffgSet(NffgSet value) {
        return new JAXBElement<NffgSet>(_NffgSet_QNAME, NffgSet.class, null, value);
    }

}
