//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:13:19 PM CEST 
//


package it.polito.verifoo.rest.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AllocationConstraint" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="type" use="required" type="{}AllocationConstraintType" />
 *                 &lt;attribute name="nodeA" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nodeB" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "allocationConstraint"
})
@XmlRootElement(name = "AllocationConstraints")
public class AllocationConstraints {

    @XmlElement(name = "AllocationConstraint")
    protected List<AllocationConstraints.AllocationConstraint> allocationConstraint;

    /**
     * Gets the value of the allocationConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allocationConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllocationConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllocationConstraints.AllocationConstraint }
     * 
     * 
     */
    public List<AllocationConstraints.AllocationConstraint> getAllocationConstraint() {
        if (allocationConstraint == null) {
            allocationConstraint = new ArrayList<AllocationConstraints.AllocationConstraint>();
        }
        return this.allocationConstraint;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="type" use="required" type="{}AllocationConstraintType" />
     *       &lt;attribute name="nodeA" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nodeB" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AllocationConstraint {

        @XmlAttribute(name = "type", required = true)
        protected AllocationConstraintType type;
        @XmlAttribute(name = "nodeA", required = true)
        protected String nodeA;
        @XmlAttribute(name = "nodeB", required = true)
        protected String nodeB;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link AllocationConstraintType }
         *     
         */
        public AllocationConstraintType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link AllocationConstraintType }
         *     
         */
        public void setType(AllocationConstraintType value) {
            this.type = value;
        }

        /**
         * Gets the value of the nodeA property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNodeA() {
            return nodeA;
        }

        /**
         * Sets the value of the nodeA property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNodeA(String value) {
            this.nodeA = value;
        }

        /**
         * Gets the value of the nodeB property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNodeB() {
            return nodeB;
        }

        /**
         * Sets the value of the nodeB property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNodeB(String value) {
            this.nodeB = value;
        }

    }

}
