//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.13 at 09:05:44 AM CET 
//


package it.polito.verifoo.rest.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NodeConstraints"/>
 *         &lt;element ref="{}LinkConstraints"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nodeConstraints",
    "linkConstraints"
})
@XmlRootElement(name = "Constraints")
public class Constraints {

    @XmlElement(name = "NodeConstraints", required = true)
    protected NodeConstraints nodeConstraints;
    @XmlElement(name = "LinkConstraints", required = true)
    protected LinkConstraints linkConstraints;

    /**
     * Gets the value of the nodeConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link NodeConstraints }
     *     
     */
    public NodeConstraints getNodeConstraints() {
        return nodeConstraints;
    }

    /**
     * Sets the value of the nodeConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeConstraints }
     *     
     */
    public void setNodeConstraints(NodeConstraints value) {
        this.nodeConstraints = value;
    }

    /**
     * Gets the value of the linkConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link LinkConstraints }
     *     
     */
    public LinkConstraints getLinkConstraints() {
        return linkConstraints;
    }

    /**
     * Sets the value of the linkConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkConstraints }
     *     
     */
    public void setLinkConstraints(LinkConstraints value) {
        this.linkConstraints = value;
    }

}
