//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 08:28:22 PM CET 
//


package it.polito.verifoo.rest.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Property complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Property">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="HTTPDefinition" type="{}HTTPDefinition" minOccurs="0"/>
 *         &lt;element name="POP3Definition" type="{}POP3Definition" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{}P-Name" />
 *       &lt;attribute name="graph" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="src" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dst" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lv4proto" type="{}L4ProtocolTypes" default="ANY" />
 *       &lt;attribute name="src_port" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dst_port" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isSat" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Property", propOrder = {
    "httpDefinition",
    "pop3Definition"
})
public class Property {

    @XmlElement(name = "HTTPDefinition")
    protected HTTPDefinition httpDefinition;
    @XmlElement(name = "POP3Definition")
    protected POP3Definition pop3Definition;
    @XmlAttribute(name = "name", required = true)
    protected PName name;
    @XmlAttribute(name = "graph", required = true)
    protected long graph;
    @XmlAttribute(name = "src", required = true)
    protected String src;
    @XmlAttribute(name = "dst", required = true)
    protected String dst;
    @XmlAttribute(name = "lv4proto")
    protected L4ProtocolTypes lv4Proto;
    @XmlAttribute(name = "src_port")
    protected String srcPort;
    @XmlAttribute(name = "dst_port")
    protected String dstPort;
    @XmlAttribute(name = "isSat")
    protected Boolean isSat;

    /**
     * Gets the value of the httpDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link HTTPDefinition }
     *     
     */
    public HTTPDefinition getHTTPDefinition() {
        return httpDefinition;
    }

    /**
     * Sets the value of the httpDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link HTTPDefinition }
     *     
     */
    public void setHTTPDefinition(HTTPDefinition value) {
        this.httpDefinition = value;
    }

    /**
     * Gets the value of the pop3Definition property.
     * 
     * @return
     *     possible object is
     *     {@link POP3Definition }
     *     
     */
    public POP3Definition getPOP3Definition() {
        return pop3Definition;
    }

    /**
     * Sets the value of the pop3Definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link POP3Definition }
     *     
     */
    public void setPOP3Definition(POP3Definition value) {
        this.pop3Definition = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link PName }
     *     
     */
    public PName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link PName }
     *     
     */
    public void setName(PName value) {
        this.name = value;
    }

    /**
     * Gets the value of the graph property.
     * 
     */
    public long getGraph() {
        return graph;
    }

    /**
     * Sets the value of the graph property.
     * 
     */
    public void setGraph(long value) {
        this.graph = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

    /**
     * Gets the value of the dst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDst() {
        return dst;
    }

    /**
     * Sets the value of the dst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDst(String value) {
        this.dst = value;
    }

    /**
     * Gets the value of the lv4Proto property.
     * 
     * @return
     *     possible object is
     *     {@link L4ProtocolTypes }
     *     
     */
    public L4ProtocolTypes getLv4Proto() {
        if (lv4Proto == null) {
            return L4ProtocolTypes.ANY;
        } else {
            return lv4Proto;
        }
    }

    /**
     * Sets the value of the lv4Proto property.
     * 
     * @param value
     *     allowed object is
     *     {@link L4ProtocolTypes }
     *     
     */
    public void setLv4Proto(L4ProtocolTypes value) {
        this.lv4Proto = value;
    }

    /**
     * Gets the value of the srcPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcPort() {
        return srcPort;
    }

    /**
     * Sets the value of the srcPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcPort(String value) {
        this.srcPort = value;
    }

    /**
     * Gets the value of the dstPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDstPort() {
        return dstPort;
    }

    /**
     * Sets the value of the dstPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDstPort(String value) {
        this.dstPort = value;
    }

    /**
     * Gets the value of the isSat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSat() {
        return isSat;
    }

    /**
     * Sets the value of the isSat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSat(Boolean value) {
        this.isSat = value;
    }

}
